DROP TABLE IF EXISTS hobbies;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS persons;


CREATE TABLE IF NOT EXISTS hobbies(
	id INTEGER AUTONUMERIC,
	name VARCHAR(100)NOT NULL,
	CONSTRAINT pk_hobbies PRIMARY KEY (id)
) 