DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS hobbies;
DROP TABLE IF EXISTS trades;

CREATE TABLE IF NOT EXISTS countries
(
	id INTEGER,
	name VARCHAR(100)NOT NULL,
	CONSTRAINT pk_countries PRIMARY KEY (id AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS hobbies
(
	id INTEGER,
	name VARCHAR(100) NOT NULL,
	CONSTRAINT pk_hobbies PRIMARY KEY (id AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS trades
(
	id INTEGER,
	name VARCHAR(100) NOT NULL,
	CONSTRAINT pk_trades PRIMARY KEY (id AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS persons
(
	id INTEGER,
	fname VARCHAR(100) NOT NULL,
	lname VARCHAR(100) NOT NULL,
	dob DATE NOT NULL,
	salary float DEFAULT 0 CHECK (salary >= 0),
	country_id INTEGER NOT NULL,
	hobby_id INTEGER NOT NULL,
	trade_id INTEGER NOT NULL,
	CONSTRAINT fk_countries FOREIGN KEY (country_id) REFERENCES countries(id)
    	ON DELETE CASCADE
    	ON UPDATE CASCADE
	,
	CONSTRAINT fk_hobbies FOREIGN KEY (hobby_id) REFERENCES hobbies(id)
    	ON DELETE CASCADE
      	ON UPDATE CASCADE
	,
	CONSTRAINT fk_trades FOREIGN KEY (trade_id) REFERENCES trades(id)
		ON DELETE CASCADE
      	ON UPDATE CASCADE
    ,
    CONSTRAINT pk_persons PRIMARY KEY (id AUTOINCREMENT)
)

